FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive
# update the base iamge
RUN apt-get update && apt-get -y update 
RUN apt install -y python3-dev python3-pip  python3-opencv vim-tiny  libopencv-dev
RUN apt install -y mosquitto-clients
#RUN pip3 install --upgrade pip setuptools wheel
RUN apt install -y libcanberra-gtk-module libcanberra-gtk3-module
RUN pip3 install Cython
RUN pip3 install torchvision
RUN pip3 install requests
RUN pip3 install numpy==1.20.3
RUN pip3 install pandas
RUN pip3 install matplotlib
RUN pip3 install paho-mqtt
#RUN pip3 install opencv-contrib-python
RUN pip3 install pyyaml tqdm
RUN pip3 install seaborn
# example from https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_video_display/py_video_display.html
COPY cam.py cam.py
ENV num_workers=1

# CMD ["export", "LD_PRELOAD=/usr/local/lib/python3.8/dist-packages/torch/lib/libgomp-d22c30c5.so.1"]
CMD ["python3","cam.py"]